spring:
  datasource:
    url: jdbc:mysql://localhost:3306/snapword?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          fetch_size: 100

translation:
  api:
    # 파파고 카드 등록/키 발급 후 여기에 채워넣기
    client-id:
    client-secret:
